# Generated by Django 4.2.7 on 2023-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertise",
            name="ad_type",
            field=models.CharField(
                choices=[("sell", "Sell"), ("buy", "Buy")],
                default="sell",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="advertise",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="advertise",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
