# Generated by Django 4.2.7 on 2023-11-16 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_advertise_ad_type_advertise_image_advertise_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
